@startuml
'https://plantuml.com/class-diagram

class Subject {
+ subject_name : string
+ marks[] : int
}

Subject *-- Student
class Student {
+ first_name : string
+ last_name : string
+ subjects[] : Subject
}

@enduml